# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Rookpawn
description: A theme for chess blogging with figurine notation, FEN diagrams, and a built-in simple PGN viewer. Forked from Athena, a simple and elegant theme for Jekyll and GitHub Pages. Requires chess.js and chessboard.js.
# baseurl: "/athena" # the subpath of your site, e.g. /blog
url: "https://satranchess2025.github.io" # the base hostname & protocol for your site
# github_repo: athena # the GitHub repo name for your project
# github_username: broccolini

# Optional social link, you can choose from the following options:
# twitter (default), instagram, medium, or dribbble
# social_link: twitter
# social_username: broccolini

# Set theme color here
# Choose from: black (default), blue, gray, magenta, orange, red, white, and yellow.
theme_color: light

# Build settings
markdown: kramdown
